-- MySQL Script generated by MySQL Workbench
-- нд, 22-жов-2017 21:03:14 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema servicedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema servicedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `servicedb` DEFAULT CHARACTER SET utf8 ;
USE `servicedb` ;

-- -----------------------------------------------------
-- Table `servicedb`.`user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicedb`.`user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicedb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicedb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_group` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_group_idx` (`user_group` ASC),
  CONSTRAINT `user_group`
    FOREIGN KEY (`user_group`)
    REFERENCES `servicedb`.`user_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
